### PR TITLE
[BUG] build system - unnecessary re-compilation

### PR DESCRIPTION
**Pull request by JaredWright**
Bug #534 

Added a macro and utility cmake script to allow installing files with
correct dependency tracking during build commands added with
ExternalProject_Add_Step

Signed-off-by: JaredWright <jared.wright12@gmail.com>

### CODE REVIEW

**Comment by connojd** [comment]
What should this patch be preventing? If it's the driver build duplication I think the issue is that there is an `execute_process` in the driver's CMakeLists.txt.  I ran this PR on my machine, and after commenting the execute_process out ithe driver wasn't rebuilt.

**Comment by JaredWright** [comment]
This PR does not address the driver build duplication, maybe I should have named the bug slightly different. The behavior that this PR addresses is that all source files in the vmm, unit tests, bfm (basically anything that isn't the driver) re-compiles all source on every build. This was because external dependencies such as json, hippomocks, newlib, etc were being re-installed into the build "install" directory on every build, thus causing all components that depend on them to rebuild as well.

You are correct, the driver does rebuild itself every time because of the issue you described. I might suggest making seperate bug report for that one. Should I change the description of bug #539 to be more specific?

**Comment by connojd** [comment]
Whatever is easier - If the driver fix is only that one line you could probably just throw it in with this one but you can make it separate if you want

**Comment by JaredWright** [comment]
It will be a little more complicated that just commenting that line out, because that line is what causes the driver to build at all under the 'all' target. I think the real solution to driver-rebuilding is to remove the need for building the driver with an external build script (scripts/util/driver_build.sh). We should have cmake compile the driver project just like anything else, potentially using a driver-specific toolchain.

**Comment by connojd** [comment]
👍

**Pull request merged**
