### PR TITLE
initial support for openSUSE

### PR DESCRIPTION
**Pull request by spockfish**

### CODE REVIEW

**Comment by rianquinn** [comment]
LGTM. Before I merge, could you squash your commits, and provide a single commit message using the following format:

https://github.com/Bareflank/hypervisor/wiki/Contributing#commit-message-format

**Comment by rianquinn** [comment]
When you update the commit message, don't forget to add the following so that the PR is cross referenced with the enhancement / conversation. 

[ISSUE]: https://github.com/Bareflank/hypervisor/issues/139

**Comment by spockfish** [comment]
guys, I'm embarrassed to admit this, but I need some help with this. What's the easiest way to do this? Close this PR and create a new one? I tried to rebase my own branche and squash the commits but I'm not sure how to continue... :-(

**Comment by rianquinn** [comment]
lol... don't be embarrassed. Nobody is worse at git than me... just ask Brendan. 

This is how I rebase for a PR:
- make sure you have a remote setup for the upstream repo. I always call mine "upstream". So it's something like "git remote add upstream https://github.com/Bareflank/hypervisor.git"
- Then, before every PR, run "git fetch upstream" to make sure you have the latest and greatest. 
- Then, "git rebase -i upstream/master". This will start the rebase. 
- An editor should come up. Here, you should see a list of commits. Each commit should be labeled "pick". Change the top most "pick" to "r" for reword, and the rest should be changed to "f" for fix up. This will squash all of the commits to the top most. Save and exit
- The editor should come back up again, but this time, it will show you the message you put it on the "top" most commit. You can now provide a new commit message. The format is provided above. Don't forget the [ISSUE] text I put above. Save and exit
- Now, all you have to do is a "git push origin <branch> -f". This will update your remote branch with the rebased code. "-f" is needed to rewrite history. Once you do this, the PR should automatically update, and Travis CI should kick off.

**Comment by spockfish** [comment]
Ok done. I think ;-)

Again impressed with and intimidated by the possibilities of git.

**Pull request merged**
