### PR TITLE
Change order of execution of delegates from FILO to FIFO

### PR DESCRIPTION
**Pull request by boddumanohar**
Signed-off-by: "Manohar Reddy" <"201451024@iiitvadodara.ac.in">

### CODE REVIEW

**Comment by connojd** [comment]
Is there a reason not change the exit handlers as well?

**Comment by boddumanohar** [comment]
https://github.com/Bareflank/hypervisor/blob/dev/bfvmm/include/hve/arch/intel_x64/exit_handler/exit_handler.h#L119

I guess exit handler already uses FIFO

**Comment by rianquinn** [comment]
Yeah, the exit handlers were already FIFO. I think I changed the exit handlers, and forgot to change this one.

**Comment by boddumanohar** [comment]
Looks like I broke the build. It built in my local machine. I checked it before pushing it.

**Comment by connojd** [comment]
yeah windows is very touchy

**Comment by rianquinn** [comment]
It appears that Cygwin is broken at the moment. I'll merge as this should get cleared up by Cygwin in the near future (usually does).

**Pull request merged**
