### PR TITLE
Build System Support for Aarch64 #498

### PR DESCRIPTION
**Pull request by JaredWright**
Added Vagrant support for the latest three versions of Ubuntu

1) Added a Vagrantfile

2) Added provisioning scripts for each version of Ubuntu

[RFC] Build System Support for Aarch64 #498

### CODE REVIEW

**Comment by JaredWright** [comment]
Question for @rianquinn and @connojd : I tested that Bareflank builds successfully in Ubunutu VMs for 16.04, 16.10, and 17.04. @cpavlina brought up a good point that we might want to just provide one ubuntu VM for vagrant so that we don't have to maintain all three. What are your  thoughts? Provide the option to build in different ubuntun ditros? Or just keep it to one version of Ubuntu?

**Comment by JaredWright** [comment]
Also, to use the provided Vagrant file, you can do the following:

```
vagrant up    # defaults to 17.10
vagrant ssh -c "cmake .. && make -j2"
```

Or you can pick a particular version of Ubuntu:
```
vagrant up ubuntu16_10   # picks the 16.10 VM
vagrant ssh ubuntu16_10 -c "cmake .. && make -j2"
```

**Comment by rianquinn** [comment]
I like the idea of having all of the versions we support so that it is easy to show instructions, but also provide scripts testing building. Couple of questions:
- Is there a way to use a different hypervisor other than VirtualBox?
- Does 6.10 need an update of cmake? We only need 3.6

**Comment by JaredWright** [comment]
1) Yes, you can use other hypervisors as the so-called "provider" for vagrant. I know that VMWare fusion is supported, and I sort-of got vagrant working with KVM at some point

2) I believe that Ubuntu 16.10 comes with cmake 3.5.2

**Comment by rianquinn** [comment]
Ok, for now, lets just support 17.04, and 17.10 moving forward. If VMWare Fusion is supported, we should leverage this to do our functional tests on the Mac Mini server we have in-house. 

The only other comment I have is put all of the apt-get install commands onto a single line as it is faster.

**Comment by JaredWright** [comment]
Ok, I removed the provisioners and configs for Ubuntu 16.04 and 16.10, but I do not have VMWare Fusion, so I can't test out changes for that. It should already support VMWare, and you can add settings the same way as there are some currently for VirtualBox

**Comment by rianquinn** [comment]
LGTM. Once the tests are done I will merge.

**Pull request merged**
