### PR TITLE
Add IntelliSense Support

### PR DESCRIPTION
**Pull request by rianquinn**
This patch adds support for IntelliSense for VSCode. Specifically, this
provide support for code completion and error checking.

Signed-off-by: “rianquinn” <“rianquinn@gmail.com”>

### CODE REVIEW

**Comment by JaredWright** [comment]
Can this be placed in the scripts directory instead of the top level?

**Comment by rianquinn** [comment]
No, it has to be at the top level, a problem consistent with most editors.

**Comment by rianquinn** [comment]
This is a feature @brendank310 and I have been trying to add for a long time, but nothing has worked until now. VSCode is pretty awesome.

**Comment by JaredWright** [comment]
The problem that I see is that it is very specific to your development environment. To me, this doesn't belong checked in to the top level.

**Comment by rianquinn** [comment]
It's not the first code completion file that we have checked into the top level. If we end up with more than one in the future that actually works, I am willing to consider a different approach.

**Comment by JaredWright** [comment]
I feel like if I made a PR to check in a .vimrc to the top level of Bareflank/hypervisor with code completion support, there would be push back from people who don't use vim...

**Comment by rianquinn** [comment]
Not from me

**Comment by JaredWright** [comment]
I'm still not a fan of this PR. If you merge this, I'll likely suggest adding a makefile target that will set up VSCode features if you so desire. I would hate to see .eclipse and .xcode and .vim and .<every_other_ide> polluting the top level of the hypervisor repo.

**Comment by rianquinn** [comment]
I moved it to scripts. I personally don't think this is an issue, but this is not something worth arguing over.

**Pull request merged**
