### PR TITLE
Initial Clang Support / Windows Cleanup

### PR DESCRIPTION
**Pull request by rianquinn**
This PR provides some initial support for Clang. There will be a PR in the future to make a change on how clang is called, which will cause another configure version tick, but will keep clang more inline with what we are doing with GCC. 

While developing this patch, I noticed that Windows was completely broken due to two issues documented here:
https://github.com/Bareflank/hypervisor/issues/213

Basically:
- Cygwin did an update that caused more GSL code to stop compiling.
- Windows did an update, which caused some of the driver code to stop compiling, which just needed a swap of some header files
- Our TLS implementation was wrong in so many ways, so I reverted those changes. This could cause stability issues with `on_success` `on_failure`, but for now it seems to work. This code will be fixed shortly in a new PR

In general, this PR should allow us to continue development and testing, including with Clang, while we sort out some issues.

### CODE REVIEW

**Comment by brendank310** [comment]
It looks like the clang support puts us beyond the time limit allowed by appveyor for free accounts.

**Comment by rianquinn** [comment]
Yeah, I am working this right now. In the end we will need to download the cross compilers, so this PR will get updated with how to do that. AppVeyor doesn't support docker, so we will basically mimic it instead. 

The harder part is were to put the cross compilers. For now I think I can make it work with DropBox, but we really need to host the file somewhere.

**Comment by rianquinn** [comment]
It's a "festivus miracle". This PR took a long time to get right. Long story short is:

- AppVeyor only gives you a hour, and Clang + GCC compiling on windows takes longer than that. 
- Needed a place to store pre-compiled Windows cross compiler. We now have a file server for this. 
- The cross compilers were originally compiled in Windows 10, which didn't work on Windows 8.1 and 2012 R2, so I had to re-compile in Windows 8.1
- Compilation of BFM on Windows is still GCC, which is fine since we really want to compile BFM and the drivers with Visual Studio at some point anyways.

**Comment by brendank310** [comment]
LGTM

**Pull request merged**
