### PR TITLE
Fix cast type in aarch64 serial MMIO methods

### PR DESCRIPTION
**Pull request by cpavlina**
Signed-off-by: Chris Pavlina <pavlinac@ainfosec.com>

### CODE REVIEW

**Comment by rianquinn** [comment]
I'm assuming it didn't compile with static_cast? Also, why are you adding the qualifier?

**Comment by cpavlina** [comment]
Indeed it does not compile with `static_cast`. In your second question are you referring to `volatile`? That's required for MMIO access; otherwise the compiler is free to assume consecutive accesses to the address will return the same value.

**Comment by rianquinn** [comment]
I'm not sure that assumption stretches beyond the confines of a function, but I'm fine with the implementation. Once this passes I will merge.

**Comment by cpavlina** [comment]
Depends whether the optimizer decides to inline the method - I've personally seen it do that. In any case it's "proper" to declare it that way whether or not the optimizer usually would mess with it.

**Comment by rianquinn** [comment]
+1

**Pull request merged**
